backend:
    name: git-gateway
    branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
# logo_url: https://codestitch.app/frontend/images/logo.png
logo_url: https://xow-mt.netlify.app/assets/images/logo-xow.webp

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
    - name: "blog"
      label: "Blog"
      folder: "src/content/blog"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

    - name: "portfolio"
      label: "Portfolio"
      folder: "src/content/portfolio"
      media_folder: "/src/assets/images/portfolio"
      public_folder: "/assets/images/portfolio"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify the project URL. If you enter "Demo Project", the post will be accessible from "portfolio/demo-project".',
            }
          - {
                label: "Tags",
                name: "tags",
                widget: "select",
                multiple: true,
                min: 1,
                max: 4,
                options: ["Animation", "Branding", "Content", "Graphic Design"],
            }
          - {
                label: "Hero Image",
                name: "heroImage",
                widget: "image",
                required: true,
            }
          - {
                label: "Hero Image Caption",
                name: "heroImageAlt",
                widget: "string",
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Supporting Text 1",
                name: "supportingText1",
                widget: "string",
                hint: "Shown above Supporting Image 1",
                required: false,
            }
          - {
                label: "Supporting Image 1",
                name: "supportingImage1",
                widget: "image",
                required: false,
                hint: "Landscape, full-width.",
            }
          - {
                label: "Supporting Image 1 Caption",
                name: "supportingImage1Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Supporting Text 2",
                name: "supportingText2",
                widget: "string",
                hint: "Shown above Supporting Image 2",
                required: false,
            }
          - {
                label: "Supporting Image 2",
                name: "supportingImage2",
                widget: "image",
                required: false,
                hint: "Landscape, full-width.",
            }
          - {
                label: "Supporting Image 2 Caption",
                name: "supportingImage2Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Supporting Text 3",
                name: "supportingText3",
                widget: "string",
                hint: "Shown above Supporting Image 3",
                required: false,
            }
          - {
                label: "Supporting Image 3",
                name: "supportingImage3",
                widget: "image",
                required: false,
                hint: "Landscape, full-width.",
            }
          - {
                label: "Supporting Image 3 Caption",
                name: "supportingImage3Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Supporting Text 4",
                name: "supportingText4",
                widget: "string",
                hint: "Shown above Supporting Image 4",
                required: false,
            }
          - {
                label: "Supporting Image 4",
                name: "supportingImage4",
                widget: "image",
                required: false,
                hint: "Portrait, left-aligned.",
            }
          - {
                label: "Supporting Image 4 Caption",
                name: "supportingImage4Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Supporting Text 5",
                name: "supportingText5",
                widget: "string",
                hint: "Shown above Supporting Image 5",
                required: false,
            }
          - {
                label: "Supporting Image 5",
                name: "supportingImage5",
                widget: "image",
                required: false,
                hint: "Portrait, right-aligned.",
            }
          - {
                label: "Supporting Image 5 Caption",
                name: "supportingImage5Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Supporting Text 6",
                name: "supportingText6",
                widget: "string",
                hint: "Shown above Supporting Image 6",
                required: false,
            }
          - {
                label: "Supporting Image 6",
                name: "supportingImage6",
                widget: "image",
                required: false,
                hint: "Landscape, full-width.",
            }
          - {
                label: "Supporting Image 6 Caption",
                name: "supportingImage6Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
