backend:
    name: git-gateway
    branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
# logo_url: https://codestitch.app/frontend/images/logo.png
logo_url: https://xow-mt.netlify.app/assets/images/logo-xow.webp

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
    - name: "blog"
      label: "Blog"
      folder: "src/content/blog"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

    - name: "portfolio"
      label: "Portfolio"
      folder: "src/content/portfolio"
      media_folder: "/src/assets/images/portfolio"
      public_folder: "/assets/images/portfolio"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify the project URL. If you enter "Demo Project", the post will be accessible from "portfolio/demo-project".',
            }
          - {
                label: "Tags",
                name: "tags",
                widget: "select",
                multiple: true,
                min: 1,
                max: 4,
                options: ["Animation", "Branding", "Content", "Graphic Design"],
            }
          - {
                label: "Hero Image",
                name: "heroImage",
                widget: "image",
                required: true,
            }
          - {
                label: "Hero Image Caption",
                name: "heroImageAlt",
                widget: "string",
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Top Image",
                name: "topImage",
                widget: "image",
                required: false,
                hint: "Landscape, full-width.",
            }
          - {
                label: "Top Image Caption",
                name: "topImageAlt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Image 2",
                name: "image2",
                widget: "image",
                required: false,
                hint: "Landscape, full-width.",
            }
          - {
                label: "Image 2 Caption",
                name: "image2Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Image 3",
                name: "image3",
                widget: "image",
                required: false,
                hint: "Landscape, full-width.",
            }
          - {
                label: "Image 3 Caption",
                name: "image3Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Image 4",
                name: "image4",
                widget: "image",
                required: false,
                hint: "Portrait, left-aligned.",
            }
          - {
                label: "Image 4 Caption",
                name: "image4Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Image 5",
                name: "image5",
                widget: "image",
                required: false,
                hint: "Portrait, right-aligned.",
            }
          - {
                label: "Image 5 Caption",
                name: "image5Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Image 6",
                name: "image6",
                widget: "image",
                required: false,
                hint: "Landscape, full-width.",
            }
          - {
                label: "Image 6 Caption",
                name: "image6Alt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
          - {
                label: "Bottom Image",
                name: "bottomImage",
                widget: "image",
                required: false,
                hint: "Landscape, full-width.",
            }
          - {
                label: "Bottom Image Caption",
                name: "bottomImageAlt",
                widget: "string",
                required: false,
                hint: "This caption will be used for screen readers.",
            }
